### ISSUE TITLE
Not working on latest windows 11 update

### ISSUE THREAD

**Issue by CitizenDroid** [TranslucentTB/TranslucentTB.github.io#3]
not working on this build.
ver: 22H2
OS  build 22621.1555
Windows Feature Experience Pack 1000.22640.1000.0

**Comment by CitizenDroid** [comment]
Found this fix 
Part A is for those that want TranslucentTB, and Part B fixes TranslucentTB and allows the Taskbar Size tweak to work again.

Of course you can do both Part A and Part B if desired.


Part A
1. Go here, scroll down a bit and download: TranslucentTB-portable-x64.zip (for 64 bit Windows 11).
2. make a folder called TranslucentTB-portable-x64 in C drive Extract the .zip file to it(assuming C:\ is where Win 11 is installed).
3. Open the folder: C:\TranslucentTB-portable-x64 ...and right click: TranslucentTB.exe and choose: Create shortcut.
4. Right click the shortcut and choose: Copy
5. Navigate to: C:\Users\user name\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup ..and in the Startup folder, right click and "paste" the shortcut. This will cause TranslucentTB to start with Windows.



Part B
1. Go here and download ViVeTool-v0.3.2.zip
2. Create a folder in C:\ called zVIVE
3. Extract the contents of the .zip file you downloaded to: C:\zVIVE
4. Open an elevated (as admin), command prompt.
5. Type: cd C:\zVIVE
6. When the prompt changes to... c:\zVive, type: vivetool /disable /id:26008830
7. Reboot the computer, TranslucentTB and Taskbar resizing, should be working again.

**Comment by sylveon** [comment]
This is the repo for the website. You want https://github.com/TranslucentTB/TranslucentTB/issues/537

**Comment by CitizenDroid** [comment]
sorry about that not sure how to navigate this site and find anything its a bit confusing again sorry for post
